# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

# platform :android do
#     desc "My application"
#     lane :distribute do
#         build_android_app(task: "assembleRelease")
#         # build_android_app is a built-in fastlane action.
#         firebase_app_distribution(
#             app: "1:769281533962:android:52dcb1c09e85b78dab97f3",
#             testers: "dinhkhanh412@gmail.com",
#             release_notes: "Hello"
#         )
#     end
# end

platform :android do
  desc "Up app"
  lane :distribute do | options |
      msg = options[:msg]
      gradle(
        task: "assemble",
        build_type: "#{ENV["BUILD_TYPE"]}",
        print_command: false,
        properties: {
          "android.injected.signing.store.file" => "#{ENV["KEY_STORE_FILE"]}",
          "android.injected.signing.store.password" => "#{ENV["STORE_PASSWORD"]}",
          "android.injected.signing.key.alias" => "#{ENV["KEY_ALIAS"]}",
          "android.injected.signing.key.password" => "#{ENV["KEY_PASSWORD"]}",
        }
      )
      # build_android_app is a built-in fastlane action.
      firebase_app_distribution(
          app: "#{ENV["FIREBASE_APP_ID"]}",
          testers: "#{ENV["LIST_TESTERS"]}",
          release_notes: msg
      )
  end
end